web-platform-tests/results-analysis

metrics/storage/storage.go
=> Port metrics/storage from wptdashboard

metrics/models.go, metrics/models_test.go, metrics/naming_test.go
=> Improve metrics lint: Docs and types names

.travis.yml, docker_build.sh, docker_start.sh, docker_stop.sh
- Initial .travis.yml
- Scriptify stopping/removing docker instance
- Error on any failure in docker_ scripts
- Nit: Consistent shell variable syntax
=> Setup Travis CI

metrics/compute/compute.go, metrics/compute/compute_test.go, metrics/run/collect_metrics.go, metrics/storage/storage.go
=> Migrate remaining 'metrics' packages

metrics/compute/compute.go, metrics/compute/compute_test.go, metrics/models.go, metrics/run/collect_metrics.go
See https://github.com/web-platform-tests/wpt.fyi/issues/92
This is a TDD PR that currently just introduces a test for what I think is the condition that's needed to fix the UI.
@mdittmer - Can you please pull this branch, and get the test to pass (which should cascadingly rectify the wpt.fyi UI?)
=> Add test for wpt.fyi#92 that fails

metrics/run/collect_metrics.go
Integrate GCP credentials file.
=> Integrate GCP credentials file

metrics/compute/compute_test.go, metrics/models.go, metrics/models_test.go, metrics/run/collect_metrics.go, metrics/storage/storage.go
Abstract API for data loading and implement consolidated (as opposed to sharded) input
=> Metrics consolidated input

metrics/run/collect_metrics.go
Add CLI flag `-consolidated_input` to use consolidated input files from GCS during metrics computation.
- Introduce CLI flag `-consolidated_input`
- Choose default GCS bucket differently according to consolidated/non-consolidated input
=> Metrics: Add flag to support consolidated input (single GCS file / run)

metrics/models.go
`...Legacy` structs contain the exact same fields, except that `TestRuns` does __not__ include the `datastore:"-"` ignore flag, which means that any data present in those fields is read from the datastore (i.e. backward compatibly).
Note, also, that the load method is altered to only load if the nested entities are already empty.
=> Add legacy TestRunMetadata structs for reading

metrics/models.go, metrics/models_test.go
Issue is the cause of https://staging.wpt.fyi/interop/ being broken.
=> Add test and fix bug for converting TestRun{Legacy}

metrics/run/collect_metrics.go
Works towards #45
Supports the `--labels=comma,separated` flag, which manifests as a query param when fetching the runs from wpt.fyi.
Example results:
https://interop-sha-param-dot-wptdashboard-staging.appspot.com/interop/?sha=04a0711307&label=stable
=> Add labels flag to collect_metrics.go

metrics/run/collect_metrics.go
Fixes https://github.com/web-platform-tests/results-analysis/issues/52 (the current breakage in staging.)
=> Fix fetch signature

metrics/run/collect_metrics.go
Adds a flag for computing the interop against a specific SHA, rather than just the latest.
Relies on https://github.com/web-platform-tests/wpt.fyi/pull/386
=> Add flag for sha

metrics/run/collect_metrics.go
Accompanies https://github.com/web-platform-tests/wpt.fyi/pull/493
=> Use new FetchRuns signature

PULL_REQUEST_TEMPLATE.md
PR to exercise https://github.com/web-platform-tests/wpt/issues/14499.
=> Remove trailing whitespace

metrics/compute/compute_test.go, metrics/models.go, metrics/run/api/api.go
Fix for https://github.com/web-platform-tests/wpt.fyi/pull/978
Avoids this repo, or that one, from being broken during the transition of landing that PR.
=> Avoid dep on wpt.fyi/shared signature

metrics/models.go, metrics/run/api/api.go, metrics/storage/storage.go
Accompanies https://github.com/web-platform-tests/wpt.fyi/pull/1063
=> Remove legacy anomalies code

.github/workflows/test.yml, .github/workflows/update_gh_pages.yml, browser-specific-failures.js, compat-2021/main.js, interop-2022/main.js, lib/browser-specific.js, test/browser-specific.js
Remove one test that fails since the code it tests was removed:
https://github.com/web-platform-tests/results-analysis/commit/9aa0606438e7d54271404a07d7e690eaf1e35057.
Fix or disable lints to make the lint pass again.
=> Run tests and lint on PRs

git-write.js, lib/browser-specific.js, lib/index.js, lib/results.js, package.json, test/browser-specific.js
But don't bother fixing line lengths for existing code.
=> Run eslint on all code

README.md
Add explanation for how to generate static end-of-year interop scores.
=> Add EOY interop score generation to README

bad-ranges.js
See https://wpt.fyi/results/?q=status%3Amissing&run_id=4794973548969984&run_id=5157687253270528
=> Exclude 09-22-2023 (only) as a bad range (experimental)

build.sh, interop-scoring/category-data.json
Adds all category data for Interop 2024 so we can begin to generate scores.
=> Begin generating scores for Interop 2024

build.sh, interop-scoring/category-data.json
This category data will be used to run the automated script that aggregates the Interop 2025 scores.
=> Add category data for Interop 2025
