web-platform-tests/results-analysis

- metrics/models.go
- metrics/models_test.go
For https://github.com/web-platform-tests/wpt.fyi/issues/44
This may temporarily break wpt.fyi which also relies on `/shared` itself.
> Migrate to wpt.fyi/shared

- Dockerfile
This avoids the following warning during build inside Docker container:
```
go: disabling cache (/.cache/go-build) due to initialization failure: mkdir /.cache: permission denied
```
@lukebjerring PTAL
> Set GOCACHE to location non-root can write to

- .travis.yml
Fixes #23 by turning YAML config for build steps into array, rather than multi-line string. Efficacy demonstrated [here](https://travis-ci.org/web-platform-tests/results-analysis/builds/373574343?utm_source=github_status&utm_medium=notification).
> Separate steps in Travis config to capture bad status codes

- metrics/storage/storage.go
Adds rate limiting to the collector (client-side), so that the server doesn't throttle us.
Sets a rate limiter for https://github.com/web-platform-tests/results-collection/issues/454 of 50 req/s, which (for a fresh run) takes ~30m (~100k files / 50req/s / 60s).
This is based on the 3000 req/m quota described here.
`go run metrics/run/collect_metrics.go`
> Add rate limiting

- .gitignore
- .travis.yml
- metrics/compute/compute.go
- metrics/compute/compute_test.go
- metrics/models.go
- metrics/run/collect_metrics.go
- metrics/storage/storage.go
Caches fetched test results file shards under `[--cache_path]/[SHA:10]/[test path]`
Helps with https://github.com/web-platform-tests/results-collection/issues/454, as the server throttles us and eventually demands authentication (throwing a 401) and this kills the Go program, forcing us to start again.
`go run metrics/run/collect_metrics.go --cache_path=foo`
> Add caching to fetched files

- metrics/run/collect_metrics.go
- metrics/storage/storage.go
Add `-pretty` flag to metrics executable (default to false). Only use clear-and-rewrite-to-terminal behaviour when `-pretty` is set.
> Add pretty flag

- metrics/models.go
- metrics/run/collect_metrics.go
- metrics/storage/storage.go
Moves the metadata models away from nested `TestRun` entities towards `TestRunIDs`, so that we don't hit the restriction in datastore of not supporting arrays of arrays.
Also: Drive-by changes the default buckets + project to the staging instances.
See the id-only entity @ https://console.cloud.google.com/datastore/entities/query?project=wptdashboard-staging&organizationId=433637338589&ns=&kind=github.com.web-platform-tests.results-analysis.metrics.PassRateMetadata
> Use TestRunIDs instead of nested entities

- metrics/compute/compute.go
- metrics/compute/compute_test.go
- metrics/models.go
- metrics/models_test.go
- metrics/run/collect_metrics.go
- metrics/storage/storage.go
Turns out we can't save __or load__ with the nested arrays, so this change expands on the backward-compatible data type we are using to drop the label field.
Fixes the https://staging.wpt.fyi/interop/ view.
> Create TestRunLegacy type which drops labels

- metrics/models.go
This PR simply adds a `RunInfo` type and a field of that type to `TestResultsReport` so that when unsharding historical runs we can add some metadata from Datastore to the report JSON (https://github.com/web-platform-tests/data-migration/issues/1).
This should not affect results-analysis itself.
> Add RunInfo to TestResultsReport

- metrics/run/collect_metrics.go
- metrics/storage/storage.go
/CC @Hexcles 
This allows scripts/code using https://github.com/web-platform-tests/data-migration to decide whether or not to use rate limiting.
> Make GCS rate limiting optional

- .travis.yml
Update Travis setup to support two classes of runs:
1. "Normal" runs: These should behave the same as before this PR was introduced;
2. "Cron" runs: These should constitute a whole matrix of runs for `{staging, prod} x {<no labels>, experimental, stable}` configurations of metrics computation.
Once this is in place we can create a daily cron job against the master branch to compute metrics.
> Setup matrix of "normal"- and "cron"-type Travis jobs

- Dockerfile
- Makefile
- metrics/compute/compute.go
- metrics/compute/compute_test.go
- metrics/logging.go
- metrics/run/api/api.go
- metrics/run/collect_metrics.go
- metrics/storage/storage.go
- Move `metrics/run/` code to `metrics/run/api`
- I'm not thrilled with this location; should it be `metrics/api`? Something else?
- Switch to flags library that supports tagging structs
- Flags are now named `--like_this` rather than `-like_this`; `Makefile` updated accordingly
- Default-value-true not supported; all default-value-true flags renamed to be inverted to preserve default behaviour
- Some flags that should be per-compute-run configurable are API params instead of config params
- When constructing new API config object from flags, preserve existing behaviour: configure output for GCS and BQ
- When using convenience `DefaultStagingComputer()` and `DefaultProdComputer()`, output to GCS only; no one has been using the BQ output tables
- `storage.Outputter` implementations check …
> Abstract metrics run

- metrics/models.go
Fixes https://github.com/web-platform-tests/wpt.fyi/issues/682
> Add time_start/end fields to legacy format

- .github/workflows/update_gh_pages.yml
- build.sh
Fixes #65.
Now we're regenerating everything from scratch on each run, including BSF, there's no reason to not regenerate everything more often. The only downside here is that we will be changing the results for the yesterday/today on multiple occasions, rather than the figures being mostly constant once they're added.
See https://github.com/Ecosystem-Infra/wpt-results-analysis/pull/70 for some earlier discussion about this basic approach prior to this change.
> Regenerate data more often

- .github/workflows/update_gh_pages.yml
- build.sh
Reverts web-platform-tests/results-analysis#80
c.f. https://github.com/web-platform-tests/results-analysis/runs/5893361160?check_suite_focus=true
I hadn't realised we failed hard if the run isn't in the cache.
> Revert "Regenerate data more often"

- lib/browser-specific.js
This allows us to give better error messages, but arguably more importantly is often useful while experimenting with changes to BSF.
> Store the full test name while computing BSF

- interop-scoring/main.js
This change removes the thrown errors in the interop scoring script that appear when a non-OK test status is observed that has not been documented and instead logs those specific tests after scoring the run. While Interop 2023 test choices are being fleshed out, these non-OK status continue to appear on an almost-daily basis, and are only being added to the list of tests in the code. Each time a new non-OK status appears, the entire series of scripts updating `gh-pages` with run data will fail, and will continue to fail until the run's name is manually added to the list of tests cleared to have a non-OK status.
Due to the situation we're currently in to make the changes for Interop 2023, I believe it is prudent to allow for these non-OK statuses to persist and not impede the updating of …
> Add logging over error throwing for non-OK tests

- interop-2022/main.js
- interop-scoring/main.js
This test had a transient timeout error on 2023-01-21 that not been repeated since. See #143.
> Add css-scroll-snap test to list of known non-OK statuses

- interop-2022/main.js
New tests are being added to older tags, which is causing the original script for Interop 2022 to fail when it encounters non-OK statuses. This PR adds the same changes described in #141 to the old 2022 script.
> Make the same logging change for 2022 script

- .github/workflows/test.yml
- .github/workflows/update_gh_pages.yml
This documents what needs to stay in sync and locks the Ubuntu version.
None of this should have any observable effect right now.
> Polish GitHub Actions workflows

- lib/runs.js
This should be a no-op change, but takes care of escaping of names and
values in a simpler way, and if it should be needed for the page token.
> Use URLSearchParams to construct wpt.fyi API URLs

- bad-ranges.js
See https://wpt.fyi/results/?q=status%3Amissing&run_id=6282678108684288&run_id=5163365977030656&run_id=5090383543926784
> Exclude 2023-07-17 (only) as a bad range (stable)

- bad-ranges.js
Many HTML tests are just not running on that range.
> Add 09/02/2023 as bad range (experimental)

- bad-ranges.js
c.f. https://wpt.fyi/results/?q=seq%28status%3Apass%20status%3A%21pass%20status%3Apass%29&run_id=5179945829007360&run_id=5129256222326784&run_id=5105446492307456 &  https://bugs.webkit.org/show_bug.cgi?id=262078
> Exclude 2023-09-20 as a bad-range on stable

- git-write.js
- lib/runs.js
We might want to start scoring mobile browsers (such as Android WebView, Chrome for Android, Chrome for iOS, or Firefox for Android) in the future, and back-filling the cache is painfully slow (as it requires downloading each run). Instead, let's just add every product to the cache, because it doesn't have a particularly significant affect on the overall size of the repo.
FWIW, I've run this manually (which takes many, many, many hours), so I can push all the new data to the cache, rather than have the GitHub Actions job struggle to do this in its time-boxed segments.
> Update web-platform-tests/results-analysis-cache with all products

- git-write.js
Regression from https://github.com/web-platform-tests/results-analysis/pull/199, because while that was awaiting review the product got removed from wpt.fyi: https://github.com/web-platform-tests/wpt.fyi/commit/8a13f910ce6c77f37ef993a4e39f366fd5babb8b
> Remove chrome_ios as a product

- interop-scoring/category-data.json
It's already included in the links in https://github.com/web-platform-tests/wpt.fyi/pull/3662.
> Include interop-2021-grid in interop-2024-layout

- .github/workflows/test.yml
- .github/workflows/update_gh_pages.yml
Even prior to #233, we might want to update these actions. We're currently getting warnings when running these: https://github.com/web-platform-tests/results-analysis/actions/runs/11058228856
> Update GitHub Actions

- build.sh
This is no longer needed, as the 2023 scores are read from [a static file in the wpt.fyi repo](https://github.com/web-platform-tests/wpt.fyi/blob/main/webapp/static/interop-2023-experimental.csv).
> Remove 2023 aggregation from script

- build.sh
The Interop 2024 scores are now frozen and read from a static file in wpt.fyi, so generating these scores is no longer needed.
> Stop generating Interop 2024 scores
